package com.taskmanagеment.commands.enums;

public enum CommandType {

    CREATENEWMEMBER,
    SHOWALLTEAMSMEMBERS,
    SHOWALLTEAMBOARDSMEMBERS,
    CREATENEWTEAM,
    ADDMEMBERTOTEAM,
    CREATENEWBOARD,
    ADDNEWBORDINTEAM,
    ADDSTEPSTOBUG,
    SHOWBUGSTEPS,
    SHOWTASKSFROMBOARDID,
    CREATENEWTASK,
    CHANGELABEL,
    SHOWTASKALLINFO,
    UNASSIGNTASKTOMEMBER,
    ADDCOMMENTTOTASK,
    CHANGEASSIGNEE,
    SHOWACTIVITY,
    REMOVECOMMENTFROMTASK,
    REMOVEBOARD,
    REMOVETASK,
    LISTALLTASKS,
    LISTTYPETASK,
    LISTTASKBYASSIGNEE;

}
